// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/unicard-variants/CosmicDark.tsx": () => import("../components/mockups/unicard-variants/CosmicDark.tsx"),
  "./components/mockups/unicard-variants/LiquidSilver.tsx": () => import("../components/mockups/unicard-variants/LiquidSilver.tsx"),
  "./components/mockups/unicard-variants/NeonCity.tsx": () => import("../components/mockups/unicard-variants/NeonCity.tsx")
};
